/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * karusellPanel.java
 *
 * Created on Feb 24, 2013, 1:31:51 AM
 */
package Views.StartPage;

import java.util.List;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author Ernst
 */
public class CarouselPanelView extends javax.swing.JPanel {

    /** Creates new form karusellPanel */
    public CarouselPanelView() {
        initComponents();
        
        if(IMatDataHandler.getInstance().favorites() != null){
            List<Product> favorites = IMatDataHandler.getInstance().favorites();
            
            if(favorites.size() < 4){
               List<Product> products = IMatDataHandler.getInstance().getProducts();
               
               for(int i = 0; i < favorites.size(); i++){
                   FeatureItemView panel = new FeatureItemView();
                   panel.setProduct(favorites.get(i));
                   karusellPanel.add(panel);
               }
               for(int i = 0; i < 4 - favorites.size(); i++){
                   int rand = (int) (products.size()*Math.random());
                   FeatureItemView panel = new FeatureItemView();
                   panel.setProduct(products.get(rand));
                   products.remove(rand);
                   karusellPanel.add(panel);
               }
            }else{
                for(int i = 0; i < 4; i++){
                   int rand = (int) (favorites.size()*Math.random());
                   FeatureItemView panel = new FeatureItemView();
                   panel.setProduct(favorites.get(rand));
                   favorites.remove(rand);
                   karusellPanel.add(panel);
               }
            }
        }else{
            List<Product> products = IMatDataHandler.getInstance().getProducts();
            
            for(int i = 0; i < 4 - products.size(); i++){
                int rand = (int) (products.size()*Math.random());
                FeatureItemView panel = new FeatureItemView();
                panel.setProduct(products.get(rand));
                products.remove(rand);
                karusellPanel.add(panel);
            }
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        titel = new javax.swing.JLabel();
        karusellPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(750, 190));

        infoPanel.setPreferredSize(new java.awt.Dimension(750, 20));

        titel.setFont(new java.awt.Font("Myriad Pro", 1, 15));
        titel.setText("Rekommenderat för dig");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(titel)
                .addContainerGap(274, Short.MAX_VALUE))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(titel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        karusellPanel.setPreferredSize(new java.awt.Dimension(750, 160));
        karusellPanel.setLayout(new java.awt.GridLayout(1, 4));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
            .addComponent(karusellPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(karusellPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel karusellPanel;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
