/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * favoritvaruPanel.java
 *
 * Created on Feb 24, 2013, 2:08:13 AM
 */
package Views.StartPage;

import Main.ShoppingCartWrapper;
import java.awt.Color;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Product;

/**
 *
 * @author Ernst
 */
public class FeatureItemView extends javax.swing.JPanel {

    private Product product;
    
    /** Creates new form favoritvaruPanel */
    public FeatureItemView() {
        initComponents();
    }

    public void setProduct(Product p) {
        IMatDataHandler dh = IMatDataHandler.getInstance();
        imageLabel.setIcon(dh.getImageIcon(p, 150, 110));
        nameLabel.setText(p.getName());
        priceLabel.setText(p.getPrice() + " " + p.getUnit());
        suffixLabel.setText(p.getUnitSuffix());
        
        this.product = p;
    }
    
    public void changeColour(){
      setBackground(new java.awt.Color(247,221,192));  //ljust
      // setBackground(new java.awt.Color(247,193,128));
    }   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        bajButton = new javax.swing.JButton();
        suffixLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        amountSpinner = new javax.swing.JSpinner();
        imageLabel = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 193, 128));
        setMaximumSize(new java.awt.Dimension(1607, 1607));
        setPreferredSize(new java.awt.Dimension(180, 170));

        infoPanel.setBackground(new java.awt.Color(247, 224, 197));
        infoPanel.setOpaque(false);
        infoPanel.setPreferredSize(new java.awt.Dimension(750, 20));

        bajButton.setBackground(new java.awt.Color(255, 255, 255));
        bajButton.setFont(new java.awt.Font("Myriad Pro", 0, 10));
        bajButton.setText("KÖP");
        bajButton.setBorder(null);
        bajButton.setBorderPainted(false);
        bajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajButtonActionPerformed(evt);
            }
        });

        suffixLabel.setFont(new java.awt.Font("Myriad Pro", 0, 10));
        suffixLabel.setText("st");

        priceLabel.setFont(new java.awt.Font("Myriad Pro", 0, 10));
        priceLabel.setText("8 kr/st");

        amountSpinner.setFont(new java.awt.Font("Myriad Pro", 0, 10)); // NOI18N
        amountSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(0.01d), null, Double.valueOf(1.0d)));

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(suffixLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(bajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(suffixLabel))
                .addContainerGap())
        );

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banan.png"))); // NOI18N

        namePanel.setBackground(new java.awt.Color(247, 224, 197));
        namePanel.setOpaque(false);

        nameLabel.setBackground(new java.awt.Color(247, 193, 128));
        nameLabel.setFont(new java.awt.Font("Myriad Pro", 0, 24));
        nameLabel.setText("Banan");

        javax.swing.GroupLayout namePanelLayout = new javax.swing.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imageLabel)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(namePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void bajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajButtonActionPerformed
    double amount = (Double) amountSpinner.getValue();
    ShoppingCartWrapper.INSTANCE.addProduct(product, amount);
}//GEN-LAST:event_bajButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JButton bajButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel suffixLabel;
    // End of variables declaration//GEN-END:variables
}
