/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FeaturePanel.java
 *
 * Created on Feb 23, 2013, 4:45:24 PM
 */
package Views.StartPage;

import Main.ShoppingCartWrapper;
import se.chalmers.ait.dat215.project.IMatDataHandler;

/**
 *
 * @author Ernst
 */
public class FeaturePanelView extends javax.swing.JPanel {

    /** Creates new form FeaturePanel */
    public FeaturePanelView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        titel = new javax.swing.JLabel();
        beskrivning = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        suffixLabel = new javax.swing.JLabel();
        amountSpinner = new javax.swing.JSpinner();
        bajButton = new javax.swing.JButton();
        bild = new javax.swing.JLabel();

        setBackground(new java.awt.Color(247, 193, 128));
        setPreferredSize(new java.awt.Dimension(750, 190));

        infoPanel.setBackground(new java.awt.Color(247, 193, 128));
        infoPanel.setPreferredSize(new java.awt.Dimension(750, 20));

        titel.setFont(new java.awt.Font("Myriad Pro", 1, 18));
        titel.setText("Korv stroganoff med ris");

        beskrivning.setFont(new java.awt.Font("Myriad Pro", 0, 11));
        beskrivning.setText("1 portion");

        priceLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12));
        priceLabel.setText("90kr");

        suffixLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12));
        suffixLabel.setText("st");

        amountSpinner.setFont(new java.awt.Font("Myriad Pro", 0, 12));
        amountSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        bajButton.setBackground(new java.awt.Color(0, 0, 0));
        bajButton.setFont(new java.awt.Font("Myriad Pro", 0, 12));
        bajButton.setText("KÖP");
        bajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(titel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beskrivning)
                .addGap(92, 92, 92)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountSpinner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suffixLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bajButton)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(suffixLabel)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titel)
                    .addComponent(beskrivning))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/korvStroganoff.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bild)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bild, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**Lägger till diverse produkter som bildar korv stroganoff. Jag lovar
     Korv stroganoff innehåller rågmjöl*/
private void bajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajButtonActionPerformed
    IMatDataHandler dh = IMatDataHandler.getInstance();
    ShoppingCartWrapper.INSTANCE.addProduct(dh.getProduct(130)  , (Integer) amountSpinner.getValue());
    ShoppingCartWrapper.INSTANCE.addProduct(dh.getProduct(93)  , (Integer) amountSpinner.getValue());
    ShoppingCartWrapper.INSTANCE.addProduct(dh.getProduct(64)  , (Integer) amountSpinner.getValue()*2);
    ShoppingCartWrapper.INSTANCE.addProduct(dh.getProduct(35)  , (Integer) amountSpinner.getValue());
}//GEN-LAST:event_bajButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JButton bajButton;
    private javax.swing.JLabel beskrivning;
    private javax.swing.JLabel bild;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel suffixLabel;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
