/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FeaturePanel.java
 *
 * Created on Feb 23, 2013, 4:45:24 PM
 */
package Views.StartPage;

import Main.ShoppingCartWrapper;
import se.chalmers.ait.dat215.project.IMatDataHandler;

/**
 *
 * @author Ernst
 */
public class FeatureRecipeView extends javax.swing.JPanel {

    /** Creates new form FeaturePanel */
    public FeatureRecipeView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        bild = new javax.swing.JLabel();
        titel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        beskrivning = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        suffixLabel = new javax.swing.JLabel();
        amountSpinner = new javax.swing.JSpinner();
        buyButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(32767, 237));
        setMinimumSize(new java.awt.Dimension(786, 237));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(786, 237));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setText("Dagens Inköpslista");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(750, 170));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(750, 170));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(750, 170));

        bild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/korvStroganoff.PNG"))); // NOI18N
        bild.setBounds(0, 0, 750, 160);
        jLayeredPane1.add(bild, javax.swing.JLayeredPane.DEFAULT_LAYER);

        titel.setBackground(new java.awt.Color(255, 136, 0));
        titel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        titel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titel.setText("Korv stroganoff med ris");
        titel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        titel.setOpaque(true);
        titel.setBounds(0, 0, 750, 21);
        jLayeredPane1.add(titel, new Integer(2));

        infoPanel.setBackground(new java.awt.Color(255, 255, 255));
        infoPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        infoPanel.setMaximumSize(new java.awt.Dimension(750, 23));
        infoPanel.setMinimumSize(new java.awt.Dimension(750, 23));
        infoPanel.setPreferredSize(new java.awt.Dimension(750, 23));
        infoPanel.setRequestFocusEnabled(false);

        beskrivning.setFont(new java.awt.Font("Myriad Pro", 0, 11)); // NOI18N
        beskrivning.setText("1 portion");

        priceLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceLabel.setText("90kr");
        priceLabel.setFocusable(false);

        suffixLabel.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        suffixLabel.setText("förp.");

        amountSpinner.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        amountSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        buyButton.setFont(new java.awt.Font("Myriad Pro", 0, 12)); // NOI18N
        buyButton.setText("Köp");
        buyButton.setMargin(new java.awt.Insets(2, 5, 2, 5));
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beskrivning)
                .addGap(488, 488, 488)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suffixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buyButton)
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suffixLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beskrivning))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPanel.setBounds(0, 147, 750, 23);
        jLayeredPane1.add(infoPanel, new Integer(3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**Lägger till diverse produkter som bildar korv stroganoff. Jag lovar
     Korv stroganoff innehåller rågmjöl*/
private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
    IMatDataHandler dh = IMatDataHandler.getInstance();
    ShoppingCartWrapper.INSTANCE.addProduct(dh.getProduct(130)  , (Integer) amountSpinner.getValue());
    ShoppingCartWrapper.INSTANCE.addProduct(dh.getProduct(93)  , (Integer) amountSpinner.getValue());
    ShoppingCartWrapper.INSTANCE.addProduct(dh.getProduct(64)  , (Integer) amountSpinner.getValue()*2);
    ShoppingCartWrapper.INSTANCE.addProduct(dh.getProduct(35)  , (Integer) amountSpinner.getValue());
}//GEN-LAST:event_buyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JLabel beskrivning;
    private javax.swing.JLabel bild;
    private javax.swing.JButton buyButton;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel suffixLabel;
    private javax.swing.JLabel titel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
