/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FeaturePanel.java
 *
 * Created on Feb 23, 2013, 4:45:24 PM
 */
package Views.StartPage;

/**
 *
 * @author Ernst
 */
public class FeaturePanelView extends javax.swing.JPanel {

    /** Creates new form FeaturePanel */
    public FeaturePanelView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        titel = new javax.swing.JLabel();
        beskrivning = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        suffixLabel = new javax.swing.JLabel();
        amountSpinner = new javax.swing.JSpinner();
        bildPanel = new javax.swing.JPanel();
        bild = new javax.swing.JLabel();
        köpButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(750, 190));

        infoPanel.setPreferredSize(new java.awt.Dimension(750, 20));

        titel.setFont(new java.awt.Font("Myriad Pro", 1, 15));
        titel.setText("Korv stroganoff med ris");

        beskrivning.setFont(new java.awt.Font("Tahoma", 0, 10));
        beskrivning.setText("1 portion");

        priceLabel.setText("90kr");

        suffixLabel.setText("st");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(titel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beskrivning)
                .addGap(46, 46, 46)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountSpinner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suffixLabel)
                .addGap(72, 72, 72))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titel)
                    .addComponent(beskrivning)
                    .addComponent(priceLabel)
                    .addComponent(suffixLabel)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/korvStroganoff.PNG"))); // NOI18N

        javax.swing.GroupLayout bildPanelLayout = new javax.swing.GroupLayout(bildPanel);
        bildPanel.setLayout(bildPanelLayout);
        bildPanelLayout.setHorizontalGroup(
            bildPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bild)
        );
        bildPanelLayout.setVerticalGroup(
            bildPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        köpButton.setBackground(new java.awt.Color(0, 0, 0));
        köpButton.setText("KÖP");
        köpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                köpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(infoPanel, 0, 675, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(köpButton)
                .addGap(25, 25, 25))
            .addComponent(bildPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(köpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bildPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void köpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_köpButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_köpButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JLabel beskrivning;
    private javax.swing.JLabel bild;
    private javax.swing.JPanel bildPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton köpButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel suffixLabel;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
