/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FirstCheckoutView.java
 *
 * Created on Feb 27, 2013, 11:18:00 AM
 */
package Views.Checkout;

import java.awt.CardLayout;
import java.util.List;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Philip
 */
public class FirstCheckoutView extends javax.swing.JPanel {

    /** Creates new form FirstCheckoutView */
    public FirstCheckoutView() {
        initComponents();
        sumOfItems.setAsSumItem();
        CheckoutShoppingItem item1 = new CheckoutShoppingItem();       
    }
    
    public void addItemToItemsHolder( ShoppingItem si){
        CheckoutShoppingItem cosi = new CheckoutShoppingItem();
        cosi.setCheckoutShoppingItem(si);
        checkoutItemsHolder.add(cosi);
    }
    
    private void clearCheckoutView(){
        checkoutItemsHolder.removeAll();
    }
    
    public void setItemsInCheckoutView( List<ShoppingItem> items ){
        if( items == null ) return;
        
        clearCheckoutView();
        
        for(ShoppingItem si : items){
            addItemToItemsHolder(si);
        }

        checkoutItemsHolder.validate();
        checkoutItemsHolder.repaint();
        
        
        
        //------------------------------------
        //Måste fixa så att totalsumman visas rätt
        //------------------------------------
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkoutItemsHolder = new javax.swing.JPanel();
        sumOfItems = new Views.Checkout.CheckoutShoppingItem();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Main.MainApp.class).getContext().getResourceMap(FirstCheckoutView.class);
        checkoutItemsHolder.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("checkoutItemsHolder.border.title"))); // NOI18N
        checkoutItemsHolder.setName("checkoutItemsHolder"); // NOI18N
        checkoutItemsHolder.setLayout(new javax.swing.BoxLayout(checkoutItemsHolder, javax.swing.BoxLayout.Y_AXIS));

        sumOfItems.setName("sumOfItems"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, sumOfItems, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, checkoutItemsHolder, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(checkoutItemsHolder, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(sumOfItems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel checkoutItemsHolder;
    private Views.Checkout.CheckoutShoppingItem sumOfItems;
    // End of variables declaration//GEN-END:variables

}
