/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJPanel.java
 *
 * Created on Feb 24, 2013, 5:42:06 PM
 */
package Views.DetailedProduct;

/**
 *
 * @author Ernst
 */
public class DetailedProductView extends javax.swing.JPanel {

    /** Creates new form NewJPanel */
    public DetailedProductView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bildPanel = new javax.swing.JPanel();
        bild = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        köpButton = new javax.swing.JButton();
        antalText = new javax.swing.JLabel();
        antalField = new javax.swing.JTextField();
        prisText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(770, 628));

        titel.setFont(new java.awt.Font("Myriad Pro", 0, 24));
        titel.setText("Banan");

        bildPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bildPanel.setEnabled(false);

        javax.swing.GroupLayout bildPanelLayout = new javax.swing.GroupLayout(bildPanel);
        bildPanel.setLayout(bildPanelLayout);
        bildPanelLayout.setHorizontalGroup(
            bildPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bildPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(bild)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        bildPanelLayout.setVerticalGroup(
            bildPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bildPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(bild)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        infoPanel.setPreferredSize(new java.awt.Dimension(750, 20));

        köpButton.setBackground(new java.awt.Color(0, 0, 0));
        köpButton.setFont(new java.awt.Font("Myriad Pro", 0, 14));
        köpButton.setText("KÖP");
        köpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                köpButtonActionPerformed(evt);
            }
        });

        antalText.setFont(new java.awt.Font("Tahoma", 0, 14));
        antalText.setText("st");

        antalField.setText("1");
        antalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antalFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                .addComponent(antalField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(antalText)
                .addGap(39, 39, 39)
                .addComponent(köpButton))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(köpButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(antalField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(antalText))
                .addContainerGap())
        );

        prisText.setFont(new java.awt.Font("Tahoma", 0, 18));
        prisText.setText("90kr/st");

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Myriad Pro", 0, 14));
        jTextArea1.setRows(5);
        jTextArea1.setText("bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan.\nbanan?\nbanan.\nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan \nbla bla bla bla bla banan bla bla bla bla bla banan bla bla bla bla bla banan.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                            .addComponent(titel))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bildPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prisText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bildPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(prisText)
                        .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void köpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_köpButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_köpButtonActionPerformed

private void antalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antalFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_antalFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField antalField;
    private javax.swing.JLabel antalText;
    private javax.swing.JLabel bild;
    private javax.swing.JPanel bildPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton köpButton;
    private javax.swing.JLabel prisText;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
