/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListOrderDetailsView.java
 *
 * Created on Feb 28, 2013, 7:16:25 PM
 */
package Views.listOrderDetails;

import ShoppingList.ShoppingListChangeListener;
import ShoppingList.ShoppingListsHandler;

/**
 *
 * @author Peter
 */
public class ListOrderDetailsView extends javax.swing.JPanel implements ShoppingListChangeListener {

    /** Creates new form ListOrderDetailsView */
    public ListOrderDetailsView() {
        initComponents();
        ShoppingListsHandler.INSTANCE.addChangeListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jList1 = new javax.swing.JList();
        detailsContainer = new javax.swing.JPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Main.MainApp.class).getContext().getResourceMap(ListOrderDetailsView.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setBackground(resourceMap.getColor("jSplitPane1.background")); // NOI18N
        jSplitPane1.setName("jSplitPane1"); // NOI18N
        jSplitPane1.setOpaque(false);

        jList1.setFont(resourceMap.getFont("jList1.font")); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFixedCellHeight(50);
        jList1.setName("jList1"); // NOI18N
        jList1.setPreferredSize(new java.awt.Dimension(50, 90));
        jList1.setVisibleRowCount(12);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jSplitPane1.setLeftComponent(jList1);

        detailsContainer.setName("detailsContainer"); // NOI18N
        detailsContainer.setOpaque(false);
        detailsContainer.setLayout(new javax.swing.BoxLayout(detailsContainer, javax.swing.BoxLayout.PAGE_AXIS));
        jSplitPane1.setRightComponent(detailsContainer);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents

private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
// TODO add your handling code here:
    System.out.println(jList1.getSelectedValue());
    
}//GEN-LAST:event_jList1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detailsContainer;
    private javax.swing.JList jList1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    public void onChange() {
        System.out.println("ListOrderView: Shopping lists changed");
    }

}
