/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListOrderDetailsView.java
 *
 * Created on Feb 28, 2013, 7:16:25 PM
 */
package Views.listOrderDetails;

import ShoppingList.ShoppingList;
import ShoppingList.ShoppingListChangeListener;
import ShoppingList.ShoppingListsHandler;

/**
 *
 * @author Peter
 */
public class ListOrderDetailsView extends javax.swing.JPanel implements ShoppingListChangeListener {

    /** Creates new form ListOrderDetailsView */
    public ListOrderDetailsView() {
        initComponents();
        updateList();
        ShoppingListsHandler.INSTANCE.addChangeListener(this);
    }
    
    /**
     * Updates the list of lists/orders
     */
    private void updateList(){
        listsContainer.removeAll();
        for(ShoppingList list : ShoppingListsHandler.INSTANCE.getShoppingLists()) {
            listsContainer.add(new ListItemView(list.getName()));
        }
        jSplitPane1.validate();
        jSplitPane1.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        listsContainer = new javax.swing.JPanel();
        detailsContainer = new javax.swing.JPanel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Main.MainApp.class).getContext().getResourceMap(ListOrderDetailsView.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N
        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setName("jSplitPane1"); // NOI18N
        jSplitPane1.setOpaque(false);

        listsContainer.setMaximumSize(new java.awt.Dimension(0, 0));
        listsContainer.setMinimumSize(new java.awt.Dimension(0, 50));
        listsContainer.setName("listsContainer"); // NOI18N
        listsContainer.setOpaque(false);
        listsContainer.setPreferredSize(new java.awt.Dimension(0, 0));
        listsContainer.setLayout(new javax.swing.BoxLayout(listsContainer, javax.swing.BoxLayout.PAGE_AXIS));
        jSplitPane1.setLeftComponent(listsContainer);

        detailsContainer.setName("detailsContainer"); // NOI18N
        detailsContainer.setOpaque(false);

        javax.swing.GroupLayout detailsContainerLayout = new javax.swing.GroupLayout(detailsContainer);
        detailsContainer.setLayout(detailsContainerLayout);
        detailsContainerLayout.setHorizontalGroup(
            detailsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
        );
        detailsContainerLayout.setVerticalGroup(
            detailsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(detailsContainer);

        add(jSplitPane1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detailsContainer;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel listsContainer;
    // End of variables declaration//GEN-END:variables

    public void onChange() {
        updateList();
    }
}
