
/*
 * ShoppingListDetailed.java
 *
 * Created on Mar 1, 2013, 11:06:32 AM
 */
package Views.listOrderDetails;

import ShoppingList.ShoppingList;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author Peter
 */
public class ShoppingListOrderDetailed extends javax.swing.JPanel {

    ShoppingList shoppingList;

    /** Creates new form ShoppingListDetailed */
    public ShoppingListOrderDetailed(Object object) {
        initComponents();

        if (object instanceof ShoppingItem) {
            jLabel1.setText("List: " + object);
        } else if (object instanceof OrderWrapper) {
            jLabel1.setText("Order: " + object);
        } else {
            setVisible(false);
            return;
        }


        


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Main.MainApp.class).getContext().getResourceMap(ShoppingListOrderDetailed.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(715, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(399, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
