/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * favoritvaruPanel.java
 *
 * Created on Feb 24, 2013, 2:08:13 AM
 */
package StartPage;

/**
 *
 * @author Ernst
 */
public class FeatureItemView extends javax.swing.JPanel {

    /** Creates new form favoritvaruPanel */
    public FeatureItemView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        köpButton = new javax.swing.JButton();
        antalText = new javax.swing.JLabel();
        antalField = new javax.swing.JTextField();
        prisText = new javax.swing.JLabel();
        titel = new javax.swing.JLabel();
        bild = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(160, 160));

        infoPanel.setPreferredSize(new java.awt.Dimension(750, 20));

        köpButton.setBackground(new java.awt.Color(0, 0, 0));
        köpButton.setText("KÖP");
        köpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                köpButtonActionPerformed(evt);
            }
        });

        antalText.setText("st");

        antalField.setText("1");
        antalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antalFieldActionPerformed(evt);
            }
        });

        prisText.setText("90kr/st");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(prisText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(antalField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(antalText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(köpButton))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(antalField)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(köpButton, 0, 0, Short.MAX_VALUE)
                        .addComponent(antalText)
                        .addComponent(prisText)))
                .addContainerGap())
        );

        titel.setFont(new java.awt.Font("Myriad Pro", 0, 24));
        titel.setText("Banan");

        bild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Framsidan/banan.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 80, Short.MAX_VALUE)
                    .addComponent(bild)
                    .addGap(0, 80, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 28, Short.MAX_VALUE)
                    .addComponent(bild, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 28, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void köpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_köpButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_köpButtonActionPerformed

private void antalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antalFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_antalFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField antalField;
    private javax.swing.JLabel antalText;
    private javax.swing.JLabel bild;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton köpButton;
    private javax.swing.JLabel prisText;
    private javax.swing.JLabel titel;
    // End of variables declaration//GEN-END:variables
}
